### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by Roos-Skywalker** [Philipp15b/MagicSigns#11]
When I am trying to create a permissions sign with a valid permission I get this error:
''You aren't able to do that! Reason: Sign is not formatted correctly!.''

I am OP and I have several plugins installed. I used fly.toggle.self as permission from the Fly plugin. This plugin always works and I have YAPP installed as my permissions plugin. I also tested it on a new account without any permissions at all; same error. Can I fix this? If so, how?

Thanks in advance, I hope to hear from you soon
Yours faithfully Roos Skywalker

**Comment by Philipp15b** [comment]
Are you sure you're using MagicSigns 1.6.0? I can't find any code that would produce an error message like this.

**Comment by Philipp15b** [comment]
Since you didn't answer, I'll close this. Report back if you still have any problems.
