### ISSUE TITLE
Color codes do not work.

### ISSUE THREAD

**Issue by MaxosEternal** [Philipp15b/MagicSigns#14]
Reason being, I've tested this on my Windows server. It works perfectly fine even with custom groups. But an exact duplicate of my files on a Linux CentOS 6 server shows no effect and can't color the signs.

You may need to re-comply the magicsign plugin in a CentOS 6 OS so it becomes more compatible to that kind of Linux, or perhaps Linux in general?  I am not a plugin developer, so I'll stay out of it. But this issue is relating to OS systems and how they react to your plugin.

If you wish I can send my files. There are no error reports so ya out of like there.

Screenshot of Windows server: http://i1275.photobucket.com/albums/y456/MaxosEternal/2013-06-18_002509_zps2628c8f0.png

Screenshot of Linux server: http://i1275.photobucket.com/albums/y456/MaxosEternal/2013-06-18_002443_zpsf7b43a88.png

Hopefully that is enough information for ya. Please do fix this soon as I'd like to use this plugin for everything that involves signs.

Other then this problem. The plugin is working perfectly fine, its functions still remain. Keep up the great work!
- Maxos

**Comment by Philipp15b** [comment]
This may be a bug in Bukkit or a problem with your permissions, because absolutely nothing in that code depends on a specific OS (or so I hope). Could you please try out [this debug version](http://philworld.de/ms180-color-perm-debug.jar) and test  creating a new sign with and without color codes?

**Comment by MaxosEternal** [comment]
Well I've discovered it was indeed my fault. You put the only permission node that involves colors in a separate page: "Colored signs"

Instead of having it in "Permissions" page like I would of expected. Perhaps to avoid confusion like this, I'd suggest putting magicsigns.color node in the "Permissions" page as well.

Also, I really recommend having the option in the config like

op-permissions: true/false

Because once someone has OP, they can use MS to promote themselves to a higher group in Groupmanager using [ccommand]. I've successfully made it so if someone does get OP, it isn't the end of the world and control is lost. But your plugin is the only back door I've found for OP's to get say; Owner or Admin, which has more power then a OP.

Many Thanks with being patient with me. Everything works just fine it appears. But I am fearful of OP's taking control of my server just because of how powerful MS is and there is no way to deny OP's MS access.
- Maxos

**Comment by Philipp15b** [comment]
> Well I've discovered it was indeed my fault. You put the only permission node that involves colors in a separate page: "Colored signs"
> 
> Instead of having it in "Permissions" page like I would of expected. Perhaps to avoid confusion like this, I'd suggest putting magicsigns.color node in the "Permissions" page as well.

Yes, I agree that's a bit confusing. I'll change that.

> But I am fearful of OP's taking control of my server just because of how powerful MS is and there is no way to deny OP's MS access.

The way I understand permission management, OP _should_ be the end of the world. OP is the owner. If anyone has OP, you _should_ have a serious problem. Because if someone can get OP, he can likely get all other permissions too. 

What you want is some permission plugin setting that disables OPs getting full permissions: PermissionsEx for example has a `permissions.allowOps` setting that can disable OPs having full rights (although I did not hear the best about PermissionsEx' internals).
