### ISSUE TITLE
Players

### ISSUE THREAD

**Issue by trusak55** [Philipp15b/MagicSigns#15]
The Players can not use the signs!!

**Comment by Philipp15b** [comment]
This is not a really helpful bug report. Of course they work. Didn't you see the link to [the troubleshooting section of the wiki](https://github.com/Philipp15b/MagicSigns/wiki#troubleshooting)? 

> Make sure the players have the correct permissions.

You checked that?

Also quoted from there:

> When reporting an issue, please explain your problem as detailed and precise as possible. Also include which Bukkit version you are using and which plugins you use.

**Comment by Philipp15b** [comment]
Closed due to unresponsiveness.
