### ISSUE TITLE
Essentials Enchant signs

### ISSUE THREAD

**Issue by bobbensun** [Philipp15b/MagicSigns#18]
Hello !! Amazing plugin, i must say. I really love it !! Congrats on a piece of work much needed :D

I have a question tho : i have already created an enchant shop with enchants predone on signs ( using essentials, but now none of the essentials signs work, just yours for my shops ). Those enchant signs don't work anymore, and was hoping to re-use them with your plugin.

Is there a way to enchant thru magicsigns ??? or would you know the essentials node to allow only their enchant signs to work without having your plugin disabled ???

Thank you !!!

**Comment by bobbensun** [comment]
nvm. figured it out :)

**Comment by Philipp15b** [comment]
By the way, I added EnchantSigns with 0a15c3aa04d7aa7b238b8b942c8dd02be9b48c3d. They'll be included in the next release.
