### ISSUE TITLE
Using spaces with commands

### ISSUE THREAD

**Issue by edster** [Philipp15b/MagicSigns#2]
I'm trying to use magicsigns to make joining my arenas automatic instead of having to type it out.

I'm using

[COMMAND]
/ma join dome

But the console then says, invalid command type /help
when I type /ma join dome manually into the console it works fine, is there something I'm doing wrong?

**Comment by Philipp15b** [comment]
Hmm, maybe this is caused by unnormal command registration of the plugin you are using. Then the command could only be used via the chat.

**Comment by edster** [comment]
Hummm no way to fix it then eh...

**Comment by Philipp15b** [comment]
Closing this now as I cannot fix it.
