### ISSUE TITLE
The signs aren't working with the essentials economy

### ISSUE THREAD

**Issue by norrd007** [Philipp15b/MagicSigns#23]
I am making the signs corectly and puutting in everything correctly but they won't work with the economy I have tried it with item however and it works!

**Comment by Philipp15b** [comment]
Do you have Vault installed? Could you please send a link to a pastebin of the server log? Thanks.

**Comment by norrd007** [comment]
We have vault

**Comment by norrd007** [comment]
and where would i find the server log? i have never used it before

**Comment by norrd007** [comment]
Wait I have it

**Comment by norrd007** [comment]
the server log is to big to copy and paste

**Comment by Philipp15b** [comment]
1. Remove/Disable all plugins that are not related to this issue (that is everything other than MagicSigns, Vault and your economy plugin)
2. Stop your server
3. Delete your old server logfile
4. Start your server 
5. Create a new sign with an economy price **and write what you've written on it here**
6. Click on it to test it
7. Stop your server
8. Post the full server logfile to http://pastebin.com/ and attach the link to the pastebin to your comment here

If you can see anything unusual in your logfile, please explain it too. This data is important for me to analyize the problem.

**Comment by norrd007** [comment]
yeah that helped but now they take the money but give no perms

**Comment by Philipp15b** [comment]
Above still applies, I need more data to help you. Also, did you check the [troubleshooting section](https://github.com/Philipp15b/MagicSigns/wiki#troubleshooting) in the wiki?

**Comment by norrd007** [comment]
28.07 15:19:13 [Server] INFO member: [Member]norrd007
28.07 15:19:13 [Server] INFO head-builder: [Head-Builder]wildrexy9
28.07 15:19:08 [Server] INFO §4Made by zachooo and javoris767!
28.07 15:19:08 [Server] INFO Warning Ground items will be removed in 20 seconds!
28.07 15:19:08 [Multicraft] Skipped 54 lines due to rate limit (30/s)
28.07 15:18:58 [Server] INFO org.bukkit.event.EventException
28.07 15:18:58 [Server] ERROR Could not pass event PlayerInteractEvent to MagicSigns v1.9.0
28.07 15:18:58 [Server] INFO ... 15 more
28.07 15:18:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_55]
28.07 15:18:58 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_55]
28.07 15:18:58 [Server] INFO at sun.reflect.GeneratedMethodAccessor497.invoke(Unknown Source) ~[?:?]
28.07 15:18:58 [Server] INFO at de.philworld.bukkit.magicsigns.MagicSignsListener.onPlayerInteract(MagicSignsListener.java:150) ~[?:?]
28.07 15:18:58 [Server] INFO at de.philworld.bukkit.magicsigns.MSMsg.send(MSMsg.java:40) ~[?:?]
28.07 15:18:58 [Server] INFO at de.philworld.bukkit.magicsigns.MSMsg.get(MSMsg.java:32) ~[?:?]
28.07 15:18:58 [Server] INFO at java.lang.String.replace(String.java:2180) ~[?:1.7.0_55]
28.07 15:18:58 [Server] INFO Caused by: java.lang.NullPointerException
28.07 15:18:58 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at net.minecraft.server.v1_7_R4.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:157) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(SourceFile:9) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(SourceFile:60) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:630) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:374) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:58 [Server] INFO org.bukkit.event.EventException
28.07 15:18:58 [Server] ERROR Could not pass event PlayerInteractEvent to MagicSigns v1.9.0
28.07 15:18:58 [Multicraft] Skipped 55 lines due to rate limit (30/s)
28.07 15:18:54 [Server] INFO org.bukkit.event.EventException
28.07 15:18:54 [Server] ERROR Could not pass event PlayerInteractEvent to MagicSigns v1.9.0
28.07 15:18:54 [Server] INFO ... 15 more
28.07 15:18:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_55]
28.07 15:18:54 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_55]
28.07 15:18:54 [Server] INFO at sun.reflect.GeneratedMethodAccessor497.invoke(Unknown Source) ~[?:?]
28.07 15:18:54 [Server] INFO at de.philworld.bukkit.magicsigns.MagicSignsListener.onPlayerInteract(MagicSignsListener.java:150) ~[?:?]
28.07 15:18:54 [Server] INFO at de.philworld.bukkit.magicsigns.MSMsg.send(MSMsg.java:40) ~[?:?]
28.07 15:18:54 [Server] INFO at de.philworld.bukkit.magicsigns.MSMsg.get(MSMsg.java:32) ~[?:?]
28.07 15:18:54 [Server] INFO at java.lang.String.replace(String.java:2180) ~[?:1.7.0_55]
28.07 15:18:54 [Server] INFO Caused by: java.lang.NullPointerException
28.07 15:18:54 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at net.minecraft.server.v1_7_R4.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:157) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(SourceFile:9) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(SourceFile:60) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:630) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:374) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:54 [Server] INFO org.bukkit.event.EventException
28.07 15:18:54 [Server] ERROR Could not pass event PlayerInteractEvent to MagicSigns v1.9.0
28.07 15:18:54 [Multicraft] Skipped 110 lines due to rate limit (30/s)
28.07 15:18:53 [Server] INFO org.bukkit.event.EventException
28.07 15:18:53 [Server] ERROR Could not pass event PlayerInteractEvent to MagicSigns v1.9.0
28.07 15:18:53 [Server] INFO ... 15 more
28.07 15:18:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_55]
28.07 15:18:53 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_55]
28.07 15:18:53 [Server] INFO at sun.reflect.GeneratedMethodAccessor497.invoke(Unknown Source) ~[?:?]
28.07 15:18:53 [Server] INFO at de.philworld.bukkit.magicsigns.MagicSignsListener.onPlayerInteract(MagicSignsListener.java:150) ~[?:?]
28.07 15:18:53 [Server] INFO at de.philworld.bukkit.magicsigns.MSMsg.send(MSMsg.java:40) ~[?:?]
28.07 15:18:53 [Server] INFO at de.philworld.bukkit.magicsigns.MSMsg.get(MSMsg.java:32) ~[?:?]
28.07 15:18:53 [Server] INFO at java.lang.String.replace(String.java:2180) ~[?:1.7.0_55]
28.07 15:18:53 [Server] INFO Caused by: java.lang.NullPointerException
28.07 15:18:53 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at net.minecraft.server.v1_7_R4.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:157) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(SourceFile:9) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(SourceFile:60) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:630) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:374) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:53 [Server] INFO org.bukkit.event.EventException
28.07 15:18:53 [Server] ERROR Could not pass event PlayerInteractEvent to MagicSigns v1.9.0
28.07 15:18:49 [Server] INFO ... 15 more
28.07 15:18:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:49 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_55]
28.07 15:18:49 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_55]
28.07 15:18:49 [Server] INFO at sun.reflect.GeneratedMethodAccessor497.invoke(Unknown Source) ~[?:?]
28.07 15:18:49 [Server] INFO at de.philworld.bukkit.magicsigns.MagicSignsListener.onPlayerInteract(MagicSignsListener.java:150) ~[?:?]
28.07 15:18:49 [Server] INFO at de.philworld.bukkit.magicsigns.MSMsg.send(MSMsg.java:40) ~[?:?]
28.07 15:18:49 [Server] INFO at de.philworld.bukkit.magicsigns.MSMsg.get(MSMsg.java:32) ~[?:?]
28.07 15:18:49 [Server] INFO at java.lang.String.replace(String.java:2180) ~[?:1.7.0_55]
28.07 15:18:49 [Server] INFO Caused by: java.lang.NullPointerException
28.07 15:18:49 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:49 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:49 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:49 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:49 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:49 [Server] INFO at net.minecraft.server.v1_7_R4.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:49 [Server] INFO at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:157) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:49 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(SourceFile:9) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:49 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(SourceFile:60) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:49 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:630) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:49 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:374) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:49 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]
28.07 15:18:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-14-gd373bc2-b3103jnks]

**Comment by norrd007** [comment]
thats what it says

**Comment by Philipp15b** [comment]
Would you please follow the instructions above? Please don't post the server log here, but to pastebin.

**Comment by Philipp15b** [comment]
Also, the log does not include the startup log lines (which are important). And I need the exact lines you wrote on the sign.

**Comment by norrd007** [comment]
ok soz

**Comment by norrd007** [comment]
http://pastebin.com/JaAn1CbF

**Comment by norrd007** [comment]
I wrote [Permission]
            essentials.fly

```
        12
```

**Comment by norrd007** [comment]
[Permission]
essentials.fly
12

**Comment by Philipp15b** [comment]
That was one of the less fun issues to debug... It seems that you are using [Aconomy](http://dev.bukkit.org/bukkit-plugins/aconomy/), a plugin not officially supported directly by Vault. I took a look at its source code and it _literally_ contains a line that returns `null` (the value responsible for the error here) every time a standard Vault method is called. Not only that, but lots of methods that have to be implemented to be Vault-compatible are incompletely defined by Aconomy in such a way that it has to blow up eventually. To sum it up, the Vault interface is horribly implemented by Aconomy and can and will not be fixed in MagicSigns. I suggest you to use a more popular economy plugin that is **not in the planning stage** and is feature complete.

**Comment by norrd007** [comment]
Thanks
