### ISSUE TITLE
Colour Mask

### ISSUE THREAD

**Issue by Drumm-** [Philipp15b/MagicSigns#3]
Hey,
There doesn't seem to be colour on sign masks. So when I mask a Teleport Sign and use "&f/ps add Drumm_" it shows that as a string, and does not become white. 
- Drumm

**Comment by Philipp15b** [comment]
You were right. Thanks for reporting!

**Comment by Philipp15b** [comment]
[You can now download the new version 1.1.2 on BukkitDev](http://dev.bukkit.org/server-mods/magicsigns/files/7-magic-signs-1-1-2/).
