### ISSUE TITLE
[FEATURE] Teleport Signs View

### ISSUE THREAD

**Issue by Drumm-** [Philipp15b/MagicSigns#4]
Would it be possible to control where the player is looking when using a Teleport Sign? It would require 2 extra parameters to the Teleport Sign, Alterntaively 1/2 Letters could be added for N, NE, etc. etc.
- Drumm_

**Comment by Philipp15b** [comment]
Version 1.2.1 will soon be available [at BukkitDev](http://dev.bukkit.org/server-mods/magicsigns/files/9-magic-signs-1-2-1/).
