### ISSUE TITLE
Rocket Sign = Moving to Fast

### ISSUE THREAD

**Issue by mentin2** [Philipp15b/MagicSigns#5]
I am having an issue with the rocket sign,
If i put a number larger than 10 for the velocity in any directions.
I get a message spammed in the console:
"[WARNING] mentin2 moved too quickly!"
I have searched the internet, and haven't really found an answer.
Found a plugin that was, supposed to remove it, but it didn't!

Please help me

**Comment by Philipp15b** [comment]
As far as I know, this is a problem introduced by Bukkit's anti-cheat mechanism. I did not find any solutions other than a [plugin](http://dev.bukkit.org/server-mods/disable-moving-too-quickly/) that removes the console spam (I didn't try it though) and allowing flying in the bukkit server config (which would allow hackers to fly on your server).

Closing this as it's impossible to fix.
