### ISSUE TITLE
Macro issue

### ISSUE THREAD

**Issue by ghost** [Philipp15b/MagicSigns#8]
I'm experiencing an odd problem. A couple of months ago I created about 30 macros for our in game "mall" using magicsigns. All of those signs work with no issues. However, anytime I create a new macro OR re-use one of the current ones in a different location in my world, those macros stop working after a server reboot yet all the ones in the mall continue to work for some reason. Do you know what the problem might be?

Macro config: http://pastebin.com/q3y5u5AD

**Comment by Philipp15b** [comment]
So creating new signs with macros doesn't work? Or do all macros on new and old signs not work anymore if you change the config file? And you're sure there were no error messages on the console?

**Comment by ghost** [comment]
The signs with macros that I had placed back in 1.4 continue to work. However, when I try to place a new macro sign, the plugin seems to randomly pick and choose which of these signs will work upon reboot. For example, yesterday I had placed 10 signs with 10 different macros. I tested each one to make sure they worked and then rebooted the server. Upon rebooting, only signs 1 through 3 were working. I then rebooted it again, and now only sign #2 is working. I've gone through this process multiple times and the results are always very random. But for whatever the reason, I can not get them to work properly.

And there are no error messages in the console.

**Comment by Philipp15b** [comment]
But that means that some signs which did not work before worked later on reboot? Could you please use the `/ms` command on signs that don't work after reboot and check whether they're currently registered as MagicSigns?

**Comment by ghost** [comment]
No, signs that did not work continue to not work. Signs that do work continue to work up until a particular reboot. I just tried the /ms command on the signs that aren't working, and they are all registered as a magic sign.

**Comment by Philipp15b** [comment]
This should be fixed by e9776c09e735043706f2966155dd0f565d325ec6 and https://github.com/Philipp15b/MagicSigns/commit/6e93789de004b433f41950b53f2953f8fe0965be.
